spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&&serverTimezone=GMT
  jpa:
    show-sql: true
#  freemarker:
#    prefer-file-system-access: false
#    此处配置为全局的，只要返回的对象为null，则不显示
#  jackson:
#    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx94681a8f915ce849
  mpAppSecret: dd908cdd96ff37f1568737f55ecd907f
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1409146202
  mchKey: cc908cdd96ff37f1568737f55ecd907f
  keyPath: /Users/cyh/Documents/code/java/java项目/dishsell/src/main/java/com/edu/cn/dishsell/path #证书的路径
  notifyUrl: http://xxx.cc/sell/pay/nnotify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
projectUrl:
  wechatMpAuthorize: http://localhost:8080
  wechatOpenAuthorize: http://localhost:8080
  sell: http://localhost:8080

  
#logging:
#  pattern:
#    console: "%d - %msg%n" #表示输出的是对应的 时间-信息
#  file: /Users/cyh/Documents/code/java/java项目/dishsell/src/main/java/com/edu/cn/dishsell/log/sell.log
#  level:
#    com.edu.cn.dishsell.logger.LoggerTest: debug
logging:
  level:
    com.edu.cn.dishsell.mapper: trace
